
name: Publish package to PyPI

on:
  release:
    types:
      - created

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dbt-ocean-spark
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
